### ISSUE TITLE
Setting HTTP headers is using an undocumented API (writeHead)

### ISSUE THREAD

**Issue by gergelyke** [actionhero/actionhero#1017]
# Undocumented use of `response.writeHead`

Description of Issue

- ActionHero version: `latest`
- Node.js version: `latest`

Instead of passing an [array](https://github.com/actionhero/actionhero/blob/master/servers/web.js#L209) to the `response.writeHead` function, an  [objects should be passed](https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers).

The problem with the current approach is that it does not enable developers to call the `response.setHeader` before the framework's call to the `writeHead` function.

What do you think?

**Comment by evantahler** [comment]
This makes a lot of sense, and is probably a hold over from long ago:

To be more explicit, we would be changing the way that actions and initializers set headers for web clients. 

From:

```js
// old
data.connection.rawConnection.responseHeaders.push(['myHeader', 'cool'])
```
to 

```js
// new
data.connection.rawConnection.responseHeaders['myHeader'] = 'cool'
```

**Comment by evantahler** [comment]
@gergelyke are you able to tackle this via pull request?

**Comment by gergelyke** [comment]
Wouldn't it make more sense to simply call this?

```
data.connection.rawConnection.setHeader('myHeader', 'cool')
```

**Comment by neilstuartcraig** [comment]
Sorry to interject but since you're looking at reimplementing the http headers behaviour, I just wanted to make sure it'll be standards compliant. A couple of things spring to mind to that end:

It's perfectly valid to set multiple versions of the same header (i forget whether that's all response headers or all)

Header names (in http 1.x) must be handled case insensitively. This matters a lot, especially once you put an http2 layer in front as http2 forces lowercase http header names. 

Sorry if that's all obvious, just thought it was worth chipping in to avoid any wasted effort.

**Comment by gergelyke** [comment]
It's okay, thanks. This is why I'd prefer using `setHeader`, because that handles everything

**Comment by gergelyke** [comment]
@evantahler I am kind of stuck - can you help me what's the purpose of `cleanHeaders`?

**Comment by evantahler** [comment]
looks like `cleanHeaders `:
- de-duplicates headers (except for set-cookie)
- lowercases headers
- ensures that no headers are sent for a HEAD request

**Comment by gergelyke** [comment]
@evantahler what do  you think: https://github.com/actionhero/actionhero/pull/1022/files?

**Comment by evantahler** [comment]
closed via https://github.com/actionhero/actionhero/pull/1022
