### ISSUE TITLE
Custom loader

### ISSUE THREAD

**Issue by billybonks** [actionhero/actionhero#1074]
I Prefer to use promises and define my tasks in a specific way that gives me pleasure, in order to do this i need to be able to load my task/action in then transform it to have the shape that actionhero framework expects it to have.

when i initially did this i tried to make it work via the config, but it seems if i put a function in the config it gets executed recursively (tried closures as well) i am currently running off a fork

https://github.com/billybonks/actionhero/commit/2093aeb6c0cfcfa4d452e84ba3b4bcdc978f5a6f#diff-af4d0f17c39abaac1efe373a4721d4ccR59

can you help me to find a way, to build this custom loader without having to fork the codebase.

this is the code i added to handle my custom task api.

my tasks look like this

```
const Task = require('../lib/task');

class SomeTask extends Task {
  async run({pullRequestOnlineId, memberId, reviewStatus}){
   }
}

module.exports = AddReview
```

if i load this task 

`SomeTask = require('./tasks/sometask')`

I can run it synchronously or asynchronously

```
sm = new SomeTask()
sm.run(params)

SomeTask.runAsync(params) //this function uses actionheros api

//  static runAsync(params){
//    debug(`running task ${this.name}`)
//    tasks.enqueue(this.name, params, 'default');
//  }
```

**Comment by evantahler** [comment]
There's a lot to unpack here!
First, why would you run a task synchronously?  Are you trying to use the same methods in an action and task?  If so, put them in an initializer!   Who would `require('./tasks/sometask')` ?

However, there have been a number of times I've been tempted to re-write actionhero's API to look more like this, ES6-class-y.  Do you like this syntax better?  Right now, ActionHero looks a lot like [next](https://github.com/zeit/next.js/), in that the file-system is the convention for loading the server (tasks live in /tasks, actions in /actions, etc).  If we want to abandon that and do a more explicit "main" file which requires everything, perhaps this style makes more sense?

**Comment by billybonks** [comment]
ye it is quite a bit of information, was worried about putting to much.

> Right now, ActionHero looks a lot like next, in that the file-system is the convention for loading the server (tasks live in /tasks, actions in /actions, etc). If we want to abandon that and do a more explicit "main" file which requires everything, perhaps this style makes more sense?

I am happy with the filesystem layout, but either a main file or a config file where custom loaders can be added would be great, i would go with a config for now since it seems like the easiest. 

>  ES6-class-y. Do you like this syntax better?

I much prefer the ES6 class syntax, but i also prefer promise chains vs callbacks, and i plan to use them when i make a similar loader for actions.

> why would you run a task synchronously

i mainly use it when i want to run the task from ah console.

Another reason why i prefer not to use api.tasks directly is it's easy for me to make a mistake with a string, but if i have to require a file, if i need to run a task node will crash if i made a mistake. so gives extra defense.

**Comment by crrobinson14** [comment]
I'm personally a little confused about the purpose here. The entire purpose of the design of ActionHero is to "decouple" the declaration of a task or action from the mechanism that invokes it. 

This is an architectural characteristic. Decoupling means you can do things like have task workers executing tasks on different servers from where they were originally enqueued (orchestrated through Redis). For actions, it makes it easier to do things like have middleware layers that define pre/post-execution handlers to add services like session management, QOS tracking, etc.

But decoupling is also a design decision. It means you do not specifically require the task from another file and directly run it. It's not so much that you CAN'T - it is that you are not supposed to. It is literally a design choice in the system to not do this, not a shortcoming but rather a strength if decoupling is something you believe is valuable.

This is 100% my personal opinion, but I think there's incredible value in the architecture and design approach of ActionHero, and you get the most value out of it when you want those things in the first place. That does NOT in any way mean there aren't "better ways" for various things. I did this myself: I have a Gist here that allows the use of async/await mechanics in Tasks and Actions so you can do linear logic processing instead of using callbacks/promises:

https://gist.github.com/crrobinson14/1750f3f6e8c0a941751b

(Note: this should be updated now that Node 8 is out with native async/await, but you get the idea.)

Just my 2c, but if you prefer a more procedural approach you might be happier with Express or Sails...

**Comment by evantahler** [comment]
Also, actionhero has [CLI commands](https://www.actionherojs.com/docs/core/cli) now! If you have `api.nameSpace.doAThing()` you can invoke it in an action, a task, and via CLI

**Comment by billybonks** [comment]
@crrobinson14 i do see how the decoupling is a strength, and if i need a server to run in the cluster that doesn't have the code to run the task, then i will call it via the string name :). @evantahler i will definitely try out the commands, my current syntax shape is 100% compatible with the way that action hero works

but i don't want to get sidetracked from what my main goal of this issue is.

right now the `initializers/tasks.js` file loads the file using `require`

https://github.com/billybonks/actionhero/blob/1b6b86fc05f502d24312fe5ef07c65380af00e4f/initializers/tasks.js#L28

```
        try {
          const collection = require(fullFilePath) <-------
          for (let i in collection) {
           ....
          }
```
I would like to see if we can find a way to change that to be
```
```
        try {
          const collection = config.loaders.task(fullFilePath) <-------
          for (let i in collection) {
           ....
          }
```
where config `config.loaders.task` would default to `require` unless overridden ?

**Comment by crrobinson14** [comment]
@billybonks I'm not challenging the approach at all, this is truly a for-my-information question: what would this approach actually do? In what use-case would you replace the `require` call with something else? Are you trying to hook the module load process at this stage?

**Comment by evantahler** [comment]
Same question as @crrobinson14!  Also, modifying how things use `require` seems to be a job for webpack or babel?

**Comment by billybonks** [comment]
@evantahler i don't think shimming require with webpack or bable is the correct course of action

@crrobinson14 this is the function that i am using atm, of course i have lost a quite a few action hero features, but i plan on iterating over the function

https://github.com/billybonks/actionhero/commit/2093aeb6c0cfcfa4d452e84ba3b4bcdc978f5a6f#diff-af4d0f17c39abaac1efe373a4721d4ccR4

**Comment by evantahler** [comment]
I'm closing this as the next version of actionHero will require that actions and tasks are ES6 classes, which can be easily extended however you like. Also, all run methods will be async methods, so there will be no ned for a promise-ify wrapper like your example!

For example: #1098
