### ISSUE TITLE
ActionHero cannot be installed globally

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#1141]
If you install actionhero globally `npm install -g actionhero` you can generate projects and run some of the CLI commands.  However, you no longer can run the server (`npm start`).

“actionhero” (the globally installed binary) has created the API object form `/global/actionhero/index.js` and has loaded all the initializers and added them there.  But then when you hit a file in your local project, it does `require('actionhero')`  In that local file, it loads `/project/node_modules/actionhero/index.js`, and that file’s `.api = {}`. (edited)

I think the solution is in every class file rather than a simple `require(../index.js)` we actually need to check the folder structure of the local environment (project_root) and load from there rather than just the relative index.js

- ActionHero Version: `18.x.x`
- Node.js Version: all
- Operating System: all

**Comment by evantahler** [comment]
Upon much reflection... we should not support this.  We should actually throw a warning if actionhero is installed globally.

**Comment by evantahler** [comment]
This can be accomplished with the `detect-installed` package

**Comment by aurasalexander** [comment]
Hey,
I think it's absolutely okay to decide to not support a global npm installation. But instead of adding another dependency tree (`detect-installed`) just to print a warning for this edge case, I would opt for a clear statement in the documentation.

I know that there is already a hint on this at [https://www.actionherojs.com/get-started/](https://www.actionherojs.com/get-started/), but it's kind of hidden there. I feel like it should be mentioned in the main documentation under [https://docs.actionherojs.com](https://docs.actionherojs.com).

Therefore I would suggest to insert a subordinate clause in the quickstart section which indicates that a global installation is not supported. Furthermore, you could link to this issue in the existing hint on the get-started page.

**Comment by evantahler** [comment]
Good ideas! 
* https://github.com/actionhero/www.actionherojs.com/commit/0e4d54b9878ed81e5d3dd286fdfd7f65c4f15c59
*
