### ISSUE TITLE
Messaging service between AH-servers 

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero#1169]
Hi!

I'm working on complex system, main part of which is ActionHero (actually it is great, thanks!). System is complicated, so I want to split it on microservices and each of them will do specific tasks.

I need a suggestion, how to communicate between nodes in system. I thinking about RabbitMQ, but have not find any good implementation.

What to you think about it? Maybe I'm missing some think?

Thank you! Have a nice day!

- ActionHero Version: `18.1.1`
- Node.js Version: `8.9.3`
- Operating System: `CentOS 7`

**Comment by evantahler** [comment]
Can you share more about how you are splitting your services? You already have 2 good options built into ActionHero: 
* use web or sockets to have one service call another in-line for concurrent requests
* have one service enqueue a task while another consumes it for asynchronous communications.

**Comment by DoctorDimon** [comment]
Actually this is financial system with several microservices:
- UserService
- AccountService
- SecureStorage
- PaymentGateway
and so on...

web or socket connections can be interrupted, as my point of view... but maybe not.

And what about the second scenario? Can you please explain it? And one more, in some cases I need something like broadcast event, can I do it with tasks approach?

Thanks for your help!

**Comment by evantahler** [comment]
Sure.  If all of your services point to the same redis instance for Tasks, you can have one service enqueue jobs, and another service actually do the work on them.  For example, say you have an email sending service.  Rather than teach all of your microservices how to talk to SendGrid, only the email service knows this, and everyone else can just publish a task `sendEmail` with the proper args to a queue called `email`, which is only ready the related service.

This, of course, only works for async activities.  If you need something to happen within the context of a user's request (ie: ask the user service if the user connecting to the AccountService is logged in), can't you just have one service make an HTTP request to the other? This may not be the fastest form of communication, but it is sure reliable (no persistance or state the connection) and scalable (load balancers are good).

**Comment by DoctorDimon** [comment]
Hi!

Thank toy for your advice! For now I have decided to use `actionhero-node-client` and i have created something like socket transport for sync actions executions. Its OK for now, but I dont know what to do with load balancing with this approach, I think i need to go HTTP for LB as you describe above!

Thanks a lot for your help!
