### ISSUE TITLE
Actions override when working with multiple config/routes.js files

### ISSUE THREAD

**Issue by walbertoibarra** [actionhero/actionhero#1202]
# Actions override when working with multiple `config/routes.js` files
When you run ActionHero with multiple `config` folders, all actions in a duplicated verb (`GET`, `POST`, `PUT`, `DELETE`) among `route.js` files get overridden.

- ActionHero Version: `18.1.3`
- Node.js Version: `8.11.1`
- Operating System: `Windows 10`

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- Create a second `config` folder and define another `route.js` file in there
- On both `route.js` files define a route on the same verb (e.g. `POST`)
- Run ActionHero with: `ACTIONHERO_CONFIG=PATH1,PATH2 npm start`
- Try to consume both of your defined routes (one should return 404)

**Comment by evantahler** [comment]
Ah! Great catch!

I believe the issue is here . https://github.com/actionhero/actionhero/blob/master/initializers/routes.js#L145.  This line assumes that we are only loading routes once, so we need to set each verb to an empty array.  However, this method will be called once for each config folder, so we are erasing old data.  

Are you able to submit a PR to fix this?

**Comment by walbertoibarra** [comment]
I don't think that's gonna work as `api.routes.loadRoutes` gets called only once when initializing https://github.com/actionhero/actionhero/blob/master/initializers/routes.js#L190 and when a file changes https://github.com/actionhero/actionhero/blob/master/initializers/actions.js#L102. Also, it expects all routes to be on `api.config.routes`.

Was thinking to add a validation here https://github.com/actionhero/actionhero/blob/master/initializers/config.js#L134 to check if file is `routes.js` and merge the route arrays instead of replacing them entirely. Any thoughts?

**Comment by evantahler** [comment]
I think you’ll need to do the merge in the routes initialized, no? Either way, writing the approparite test will help ensure it is solver properly

As this is a loader, I’m not overly concerned with performance, so if it works, it works!

**Comment by evantahler** [comment]
Ping! Any progress on your solution?  Need any help?

**Comment by walbertoibarra** [comment]
Hi, sorry, was a little busy, but yes, I kind of have a solution, here's the [commit](https://github.com/walbertoibarra/actionhero/commit/6b43565f8abedd26e01d1d3d94bc234e5e3021f4).

I'm just unsure of how can I test this new behavior, can you point me to the right direction?

**Comment by evantahler** [comment]
Cool! 

Since we are talking about reading files from the file system, I think you'll need an integration test that really does read & write files.  The good news is that there is already a test harness for this type of thing here https://github.com/actionhero/actionhero/blob/master/__tests__/core/cli.js

* Make a new describe block for this test
* make a route in the normal `config/routes.js`
* in the `beforeAll`, write a new config folder with a new routes file
* start the server with both config paths
* make a request to a route from the normal path and the new config path
* in the `afterAll` delete the new config file
