### ISSUE TITLE
unable to add new property to data.params in action

### ISSUE THREAD

**Issue by m-yazdani** [actionhero/actionhero#1230]
# Name of Issue
unable to add new property to data.params in action

- ActionHero Version: `18.1.3`
- Node.js Version: `8.10.0`
- Operating System: `( Windows 10)`

# Steps to reproduce your error
- i want to add new property to data.params as below: but it throw an exception which says: cannot add property personId, object is not extensible
 async run(data) {
        try {
            data.params['personId'] = data.connection.globalParams.currentSystemChartId;
            let result = await api.services.Users.getPersonGlobalInfo(data.params)
            data.response = api.globals.createResponse(result);
        } catch (err) {
            api.log(err, 'error', err);
            throw err;
        }
    }

**Comment by evantahler** [comment]
This is by design.  `data.params` is [frozen](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze), as it should always represent the state of the connection's inputs.  If you want to append data to the connection, don't use params... why not just `data.personId`?
