### ISSUE TITLE
Adding custom properties to Action template 

### ISSUE THREAD

**Issue by inian** [actionhero/actionhero#1374]
# Name of Issue
Unsure of how to add custom properties to action template when using version v21 with typescript support. 

- ActionHero Version: `21.x.x`

# Steps to reproduce your error
I am trying to custom properties to the action template like [here](https://github.com/actionhero/actionhero/blob/2c1816bf399991b057367a965fba747c5f13248b/__tests__/core/middleware.ts#L81)

But I am getting a typescript error saying `Property authenticated does not exist on ..`. How do I extend the type definition of the Action class? 

If Action type was declared as an interface, I could have extended it via [Declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) but AFAIK Action is [declared as a class](https://github.com/actionhero/actionhero/blob/31458cd93537b0b054dfee13771fab43dc139802/src/classes/action.ts) and there is no way for me to extend types for that. 

I can create a new class which extends Action and declare types with the authenticated property types I guess, but seems messy. If Action was defined as an interface, it might be easier. 

PS - I am new to Typescript, so might be missing something here.

**Comment by evantahler** [comment]
Great finding!

My understanding is that interfaces cannot have methods themselves.  That means that things like `action.validate` ([here](https://github.com/actionhero/actionhero/blob/master/src/classes/action.ts#L83-L103)) couldn't be included on the class via inheritance.   

Having all Actions/Tasks/etc inherit from a common class is also helpful for testing and introspection. 

We could loosen the type definitions to allow `{[key: string]: any}` as a loose way to append methods/properties, but that seems to disagree with the notion of strongly typing things... 

Could you share why making a new base class wouldn't work for you?  I'm also new to Typescript, but I think the point is that adding properties to things arbitrarily like we used to is highly discouraged (because then you cannot ensure that all the properties are set, etc).  Extending a new class is a great way to ensure this. 

```ts
import { Action } from 'actionhero'

export abstract class AuthenticatedAction extends Action {
  authenticated: boolean

  constructor () {
    super()
    this.authenticated = true
  }
}

export SecretActon extends AuthenticatedAction {
  ...
}
```

**Comment by inian** [comment]
Yeah, I don't think setting `{[key: string]: any}` is a good idea either.

What about declaring an ActionInterface with the required properties and method signatures? [This example](https://www.typescriptlang.org/docs/handbook/interfaces.html#implementing-an-interface) shows that this should be possible. And we can have Action as an abstract class implementing that Interface. 

That way I can just extend the interface without declaring a new Class

**Comment by evantahler** [comment]
Can you show an example of what you have in mind?  I am under the impression that an `interface` cannot have any methods defined on it (although you can say that a key *should* be a method, i.e. `validate: Function`.  I think that it would be important that folks do not need to create thier own `validate` method on each action.  So... I think moving to interfaces would also require the initializer to handle the validation as well

**Comment by evantahler** [comment]
The more I read about this, the more I'm learning that the functionality you are describing is an anti-pattern in typescript.  The whole goal of strongly-typed constructors and classes is that adding properties directly (ie: `action.authenticated = true`) means that you are not following the interface as described.  The way around this is to extend the class with a new interface that clearly described the new property and that is is a boolean.   As such, I'm going to mark this as "will-not-fix", but I'll add an explicit test showing how this behavior should be accomplished now. 

See https://github.com/actionhero/www.actionherojs.com/pull/74

**Comment by inian** [comment]
Hey @evantahler ya I think extending the Action class is probably the best way to go ahead..thanks for looking into this.
