### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ricardograca** [actionhero/actionhero#1401]
# Add a changelog
There should be a changelog so that developers can know what changes were introduced with each version without having to scroll through endless pages of GitHub releases.

# Steps to reproduce your error
- Open https://github.com/actionhero/actionhero in your browser
- Try to locate the CHANGELOG.md file

## Expected

- There is a CHANGELOG.md file

## Actual

- There is no CHANGELOG.md file

**Comment by evantahler** [comment]
Thanks for the suggestion @ricardograca!

A few questions on how this might be the most useful for you:
* How far back should we go?  We've got over 200 releases... this could be a big file... 
* Do you know of a tool to generate the Changelog.md from Gihub releases?  That would be a nice workflow which we could run as part of publishing the package.  We are going to keep Github Releases as the source-of-truth for release information because tools like Greenkeeper and NPM parse this information directly now

**Comment by ricardograca** [comment]
Ideally all the way back :sweat_smile: but I realize that's not practical. If it's too hard, maybe start with the next release and go from there.

I'm not aware of any tool to generate the changelog from GitHub releases, but it's possible to have it automatically generated if using [semantic release](https://github.com/semantic-release/semantic-release) with a standard commit message format, but that's outside the scope of this feature request.

If it's any help in Bookshelf we just copy + paste the release notes into the changelog file. Example:

- [Changelog](https://github.com/bookshelf/bookshelf/blob/master/CHANGELOG.md#change-log)
- [Release notes](https://github.com/bookshelf/bookshelf/releases/tag/1.1.0)

**Comment by evantahler** [comment]
Makes sense!   
We used to have a CHANGELOG years ago, and I can't really remember why we removed it.   I'm happy to add one back.  Do you feel like making a PR for some of the recent changes to get it started?

**Comment by ricardograca** [comment]
Yes, I can do that.

**Comment by evantahler** [comment]
Hi @ricardograca, just checking in!  We will have a new version out soon, and this would be a great time to add the CHANGELOG

**Comment by evantahler** [comment]
Closing due to no response.
