### ISSUE TITLE
www site should have a key concepts page

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#1471]
Similar to https://loopback.io/doc/en/lb4/Concepts.html.  We should explain the main sections of Actionhero applicable to new developers.  What's the same, what's the difference.

**Comment by evantahler** [comment]
Topics could include:

## Actions
* like controllers, but for all servers/transports
* routing is handled by the server
* Should be stateless
* Should be "small" and pass off heavy lifting to models or service objects

## Tasks
* Background jobs
* Can be enqueued now or delayed
* Can be one-off or recurring
* Common patterns
  * short and idempotent
  * calling one task from another
  * mark-and-sweep
* Handy plugins: `ah-resque-ui`

## Chat 
* What's a chat room?  It can be used for 2-way communication for any topic (not just chat) 
* Stateful
* Works across servers
* For all types of connections

## Initializers
* How to connect to databases, storage, etc
* Your place for building service objects. 

## Servers
* Web and Websocket included
* Socket (TCP) availabl
* You can make custom ones (twitter, SOAP, etc)!

## Tests
* Jest
* `specHelper`
  * run action
  * run tasks
* 

--- 

What Actionhero doesn't have (and why)

## Models
* We are backend agnostic
* Can use files, redis, databases, etc
* Handy plugins: `ah-sequelize-ui`

## Views
* This is an API server!
* Flat-file server included though

**Comment by y471n** [comment]
Looks really good. Let's keep it to basics only. And to dive deeper maybe a section called: Deep Dive so that further details are added in there. 

eg: Actions, all the pints which are covered here. and in Deep Dive section, the Action points which are already on the website like extending Actions etc.

From the top of my head, a few points I might want to see. (Will think over and add more later)

- Standard MVC vs ActionHero (or how can we incorporate MVC with action mindset.
- Modules are missing, or are they better in the tutorial itself.
