### ISSUE TITLE
Recurring tasks should never present the "Job already enqueued at this time with same arguments" error

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#1640]
Node-resque has safety around enqueuing the same task/job in the future with the same arguments.  This is because we use a set to store future jobs, and the arguments would be de-duplicated int the set otherwise.

https://github.com/actionhero/node-resque/blob/42fc9b32d7dfbf5c7aadd04e251c75db5852781d/src/core/queue.ts#L98-L100

When actionhero boots up, there are some conditions in which we may double-enqueue a recurring task, and see this error.  That's OK, and we should suppress this error.

**Comment by mfvargo** [comment]
I've run into this issue with one of my tasks.  I had a use case where the same task would get enqueued twice from very different parts of my code. (design issue? who knows).  I was surprised by the exception as it was not documented. 

If tasks are truly meant to be idempotent and disposable then a default behavior of not double queuing them with the same args seems like the expected behavior.  But that might lead to sloppy programming on users of the api (like me) who would just task.enqueueIn() all the time without knowing they are double/triple/etc enqueueIn()'ing un-necessarily.

I think keeping the actions simple and separate lends itself to events leading to tasks that could duplicate from far reaching code locations making the de-duping of task enqueueIn() calls difficult.  I support the idea of suppressing the error.

**Comment by evantahler** [comment]
👍 

I think the error is a good thing when being used pragmatically, and a bad thing for recurring tasks.   So, I think the "ignoring" part of this story should be done by the task-reenqueue and not a "fundamental" change of node-resque.

**Comment by evantahler** [comment]
I feel pretty happy with https://github.com/actionhero/actionhero/pull/1641
