### ISSUE TITLE
"TypeError: actionhero.Process is not a constructor " when running jest

### ISSUE THREAD

**Issue by maxLogvynyuk** [actionhero/actionhero#1715]
# TypeError: actionhero.Process is not a constructor 

Description of Issue

- Actionhero Version: `25.0.4`
- Node.js Version: `14.13.0`
- Operating System: `(Linux Mint 20)`
- repo -  https://github.com/maxLogvynyuk/actionhero-boilerplate
- branch dev/streams

# Steps to reproduce your error

Run script test ( "test": "jest",) and get next error:
![actionhero_1Process](https://user-images.githubusercontent.com/59360889/106919226-9d3c9e80-6712-11eb-9381-c7727ca0687c.png)

Jest configuration:
  "jest": {
    "testEnvironment": "node",
    "moduleDirectories": [
      "node_modules"
    ],
    "moduleFileExtensions": [
      "js",
      "jsx",
      "ts",
      "tsx",
      "json"
    ],
    "transform": {
      "^.+\\.ts?$": "ts-jest"
    }
  }

server.ts

![image](https://user-images.githubusercontent.com/59360889/106920406-b8f47480-6713-11eb-9a7d-4b1c5b895c30.png)

Console in server.js after build and executing jest show next:
![image](https://user-images.githubusercontent.com/59360889/106919893-37044b80-6713-11eb-8bec-9f0158881296.png)

Seems like  class  Process don`t importing.

I have some tests and passed successfully only first every time.

Example of test:
![image](https://user-images.githubusercontent.com/59360889/106921677-e7bf1a80-6714-11eb-9eae-562c849326a4.png)

**Comment by evantahler** [comment]
Thanks for sharing the code!  
The quick answer is that the problem comes form the `export const PWD: string = path.join(process.cwd())` in your `server.ts`.  Remove it, and you'll be OK. If you want to share a value like that, you can make a new config file (`config/path.ts`) and it will become available in `config.paths.path` or however you set it for use throughout the app. 

The reason for the problem is that you've created a circular dependency: `server -> actionhero -> config`. But... config also relies on PATH from server.  Typescript can't sort out who to load first.

**Comment by maxLogvynyuk** [comment]
Thanks Evan. Removing this const solved problem.
