### ISSUE TITLE
[Bug]: Missing package  @types/glob  and deprecated PromiseValue method.

### ISSUE THREAD

**Issue by dturton** [actionhero/actionhero#2295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

node: v16.16.0
npm: 8.19.2
macOS: 12.6

mkdir ~/project && cd ~/project
npx actionhero generate
npm install

```
node_modules/actionhero/dist/modules/specHelper.d.ts:21:186 - error TS2694: Namespace '"/Users/xx/Downloads/xxx/node_modules/type-fest/index"' has no exported member 'PromiseValue'.

21     function runAction<A extends Action | void = void>(actionName: string, input?: Partial<SpecHelperConnection> | Record<string, any>): Promise<(A extends Action ? import("type-fest").PromiseValue<ReturnType<A["run"]>> : {

```

### Expected Behavior

Should not produce error

### Environment

node: v16.16.0
npm: 8.19.2
macOS: 12.6
actionhero: 28.1.12

**Comment by dturton** [comment]
Potential solution is to run npm i --save-dev @types/glob.

Replace type-fest/PromiseValue with Awaited type
[#(https://github.com/microsoft/TypeScript/pull/45350)](https://github.com/microsoft/TypeScript/pull/45350#issue-963139785)

**Comment by evantahler** [comment]
Thanks for this report! 

Rather than merge in your PR (https://github.com/actionhero/actionhero/pull/2296), I think https://github.com/actionhero/actionhero/pull/2297 is a better way to proceed. The project has other dependencies on type-fest that I want to keep for now.  

The good news is that `type-fest` just came out with [v3](https://github.com/sindresorhus/type-fest/releases/tag/v3.0.0), which under-the-hood, uses the built-in awaited type.

**Comment by evantahler** [comment]
Closed via https://github.com/actionhero/actionhero/pull/2297

**Comment by evantahler** [comment]
And `@types/glob` is added to newly generated projects via https://github.com/actionhero/actionhero/pull/2298
